// Rebuild the committed preview PNGs and static metadata with: npm run social:build
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const root = fileURLToPath(new URL('../', import.meta.url));
const logo = readFileSync(join(root, 'public/grapevine-white.png')).toString('base64');
const escape = value => value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages = [
 {slug:'home',file:'index.html',path:'/',title:'Jonathan Telep — Software engineer & builder',desc:'The universe is possible. Explore software, independent projects, and useful tools built by Jonathan Telep in Cleveland, Ohio.',lines:['the universe','is possible.'],label:'JONATHAN TELEP / SOFTWARE ENGINEER',sub:['Building ideas into things you can use.','Cleveland, Ohio · Founder of Telep IO'],accent:'#ffa665'},
 {slug:'terminal',file:'terminal.html',path:'/terminal',title:'Interactive Terminal — Jonathan Telep',desc:'Explore Jonathan Telep’s projects, live systems, and developer tools through an interactive terminal.',lines:['a different','way to explore.'],label:'INTERACTIVE TERMINAL',sub:['Projects. Commands. A little curiosity.','Step inside Jonathan Telep’s workspace.'],accent:'#a8e6a0'},
 {slug:'postgres',file:'apps/postgres/frontend/index.html',path:'/postgres/',title:'Visualize Postgres — SQL to data model',desc:'Turn PostgreSQL DDL into organized, interactive entity relationship diagrams. Explore your schema and export a professional data model document.',lines:['see the shape','of your data.'],label:'VISUALIZE POSTGRES',sub:['SQL → relationships → clarity.','Interactive diagrams. Beautiful model documents.'],accent:'#74d9f3'},
 {slug:'jsonify',file:'apps/jsonify/index.html',path:'/jsonify/',title:'Jsonify — Make sense of your JSON',desc:'Format, inspect, and explore JSON in a clean, collapsible tree. Private by design: your data stays in your browser.',lines:['a little order.','a lot of clarity.'],label:'JSONIFY / JSON EXPLORER',sub:['Format. Fold. Find your way.','Your JSON stays in your browser.'],accent:'#c2a3ff'},
];
function art(page) {
 if(page.slug==='home') return `<defs><radialGradient id="sun"><stop stop-color="#fff0c9"/><stop offset=".42" stop-color="#ffb66f"/><stop offset=".76" stop-color="#ed6236"/><stop offset="1" stop-color="#883631"/></radialGradient><radialGradient id="halo"><stop stop-color="#fb8044" stop-opacity=".4"/><stop offset="1" stop-color="#fb8044" stop-opacity="0"/></radialGradient></defs><circle cx="969" cy="314" r="320" fill="url(#halo)"/><g fill="none" stroke="#f5c0a0" stroke-opacity=".2"><ellipse cx="969" cy="314" rx="295" ry="94" transform="rotate(-38 969 314)"/><ellipse cx="969" cy="314" rx="256" ry="230"/><circle cx="969" cy="314" r="190"/></g><circle cx="969" cy="314" r="143" fill="url(#sun)"/><circle cx="778" cy="463" r="7" fill="#ffe1b9"/><text x="965" y="534" text-anchor="middle" fill="#b18d7d" font-size="12" letter-spacing="4">IDEAS INTO ORBIT</text>`;
 if(page.slug==='postgres') return `<g stroke="#74d9f3" stroke-width="2" fill="none"><path d="M856 239 H897 V382 H930"/><path d="M856 209 H1074 V316"/></g>${table(698,162,'users',['PK  id','    email','    created_at'],page.accent)}${table(930,316,'projects',['PK  id','FK  user_id','    name'],page.accent)}<circle cx="897" cy="285" r="5" fill="#74d9f3"/><text x="895" y="525" text-anchor="middle" fill="#718d9b" font-size="12" letter-spacing="3">EVERY CONNECTION, CLEAR.</text>`;
 const lines = page.slug==='terminal' ? [['$',' whoami'],['','jonathan telep'],['$',' ls projects/'],['','telep.tools  sumvid  boards'],['$',' build something great'],['','▌']] : [['{',''],['','  "project": "something great",'],['','  "status": "ready to ship",'],['','  "ideas": ['],['','    "explore", "build", "share"'],['','  ]'],['}','']];
 return `<g transform="translate(687 157)"><rect width="445" height="337" rx="15" fill="#0e1725" stroke="#ffffff" stroke-opacity=".14"/><path d="M0 45 H445" stroke="#ffffff" stroke-opacity=".1"/><circle cx="24" cy="23" r="5" fill="#ff7d80"/><circle cx="43" cy="23" r="5" fill="#eac176"/><circle cx="62" cy="23" r="5" fill="#8acaab"/><text x="423" y="27" text-anchor="end" fill="#6f859a" font-size="11">${page.slug==='terminal'?'~/workspace':'document.json'}</text>${lines.map(([prompt,line],i)=>`<text x="25" y="${88+i*32}" fill="${i%2===0?page.accent:'#bac5d2'}" font-size="${page.slug==='terminal'?17:16}" font-family="monospace">${escape(prompt+line)}</text>`).join('')}</g>`;
}
function table(x,y,name,rows,accent){return `<g transform="translate(${x} ${y})"><rect width="196" height="162" rx="10" fill="#102233" stroke="${accent}" stroke-opacity=".6"/><path d="M0 44 H196" stroke="${accent}" stroke-opacity=".3"/><text x="18" y="28" fill="${accent}" font-size="20" font-weight="600">${name}</text>${rows.map((r,i)=>`<text x="18" y="${75+i*30}" fill="#b4cada" font-size="14" font-family="monospace">${r}</text>`).join('')}</g>`;}
function svg(page){return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><defs><linearGradient id="bg" x2="1" y2="1"><stop stop-color="#101b2b"/><stop offset="1" stop-color="#050910"/></linearGradient><pattern id="grid" width="60" height="60" patternUnits="userSpaceOnUse"><path d="M60 0 H0 V60" fill="none" stroke="#7896ae" stroke-opacity=".055"/></pattern></defs><rect width="1200" height="630" fill="url(#bg)"/><rect width="1200" height="630" fill="url(#grid)"/>${Array.from({length:70},(_,i)=>`<circle cx="${(i*173+31)%1200}" cy="${(i*89+17)%630}" r="${i%3===0?1.2:.6}" fill="#cfe8ff" opacity="${i%3===0?.3:.13}"/>`).join('')}<g font-family="Arial, sans-serif">${art(page)}<rect x="60" y="61" width="5" height="21" rx="2" fill="${page.accent}"/><text x="81" y="77" fill="${page.accent}" font-size="13" font-weight="600" letter-spacing="2.5">${page.label}</text><text x="60" y="255" fill="#f3f6fa" font-size="69" font-weight="700" letter-spacing="-3">${page.lines[0]}</text><text x="60" y="335" fill="${page.accent}" font-size="69" font-weight="700" letter-spacing="-3">${page.lines[1]}</text>${page.sub.map((line,i)=>`<text x="63" y="${396+i*30}" fill="#9cacbd" font-size="18">${escape(line)}</text>`).join('')}<path d="M60 538 H1140" stroke="#b5d1e8" stroke-opacity=".15"/><image href="data:image/png;base64,${logo}" x="64" y="552" width="25" height="40"/><text x="104" y="579" fill="#e2e9f1" font-size="16" font-weight="600">telep io<tspan fill="#708094" font-weight="400"> / independent by design</tspan></text><text x="1138" y="579" fill="#a3b5c8" text-anchor="end" font-size="15">jonathantelep.com${page.path==='/'?'':page.path.replace(/\/$/,'')}</text></g></svg>`;}
const output=join(root,'public/social');mkdirSync(output,{recursive:true});
const temp=mkdtempSync(join(tmpdir(),'telep-social-'));
try {
 for(const page of pages){
  const image=`https://jonathantelep.com/public/social/${page.slug}-v1.png`;
  const url=`https://jonathantelep.com${page.path}`;
  const tags={ 'og:type':'website','og:site_name':'Jonathan Telep','og:locale':'en_US','og:title':page.title,'og:description':page.desc,'og:url':url,'og:image':image,'og:image:secure_url':image,'og:image:type':'image/png','og:image:width':'1200','og:image:height':'630','og:image:alt':`${page.label}: ${page.lines.join(' ')}`, 'twitter:card':'summary_large_image','twitter:creator':'@telep_io','twitter:title':page.title,'twitter:description':page.desc,'twitter:image':image,'twitter:image:alt':`${page.label}: ${page.lines.join(' ')}`};
  const metadata=`    <!-- social-preview:start -->\n    <meta name="description" content="${escape(page.desc)}">\n    <link rel="canonical" href="${url}">\n`+Object.entries(tags).map(([key,value])=>`    <meta ${key.startsWith('og:')?'property':'name'}="${key}" content="${escape(value)}">`).join('\n')+'\n    <!-- social-preview:end -->';
  const file=join(root,page.file);
  let html=readFileSync(file,'utf8').replace(/\s*<!-- social-preview:start -->[\s\S]*?<!-- social-preview:end -->/g,'').replace(/\s*<meta (?:name|property)="(?:og:[^"]*|twitter:[^"]*|description)"[^>]*>/g,'').replace(/\s*<link rel="canonical"[^>]*>/g,'').replace(/\s*<!-- (?:Open Graph|Twitter Card|Canonical) -->/g,'');
  html=html.replace(/<\/title>/,`</title>\n${metadata}`);
  writeFileSync(file,html);
  const source=join(temp,`${page.slug}.html`);
  writeFileSync(source,`<!doctype html><html><head><style>*{margin:0}body{width:1200px;height:630px;overflow:hidden}</style></head><body>${svg(page)}</body></html>`);
  const result=spawnSync(process.env.CHROMIUM || 'chromium',['--headless','--no-sandbox','--disable-gpu',`--user-data-dir=${join(temp,'browser')}`,'--hide-scrollbars','--force-device-scale-factor=1','--window-size=1200,630',`--screenshot=${join(output,`${page.slug}-v1.png`)}`,`file://${source}`],{encoding:'utf8'});
  if(result.status!==0)throw new Error(result.stderr || 'Chromium failed to render social card');
  console.log(`Generated ${page.slug} social card and metadata.`);
 }
} finally {rmSync(temp,{recursive:true,force:true});}
